version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    restart: always
    ports:
      - "5678:5678"
    environment:
      # Configuración básica
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      
      # Configuración de webhooks
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=${N8N_PORT}
      - N8N_PROTOCOL=http
      
      # Configuración de base de datos (SQLite por defecto)
      - DB_TYPE=sqlite
      - DB_SQLITE_DATABASE=/home/node/.n8n/database.sqlite
      
      # Configuración de logs
      - N8N_LOG_LEVEL=info
      
      # Configuración de webhooks
      - WEBHOOK_URL=${N8N_WEBHOOK_URL}
      
    volumes:
      # Persistir datos de n8n
      - n8n_data:/home/node/.n8n
      
      # Para desarrollo: montar workflows locales (opcional)
      # - ./workflows:/home/node/.n8n/workflows
      
    networks:
      - n8n-network
  waha:
    image: devlikeapro/waha:latest
    restart: always
    ports:
      - "3001:3000"  # Cambiamos el puerto para evitar conflictos con n8n
    environment:
      - WAHA_BASE_URL=${WAHA_BASE_URL}
      - WAHA_AUTHENTICATION_DASHBOARD_USERNAME=${WAHA_AUTHENTICATION_DASHBOARD_USERNAME}
      - WAHA_AUTHENTICATION_DASHBOARD_PASSWORD=${WAHA_AUTHENTICATION_DASHBOARD_PASSWORD}
      - WAHA_AUTHENTICATION_SWAGGER_USERNAME=${WAHA_AUTHENTICATION_SWAGGER_USERNAME}
      - WAHA_AUTHENTICATION_SWAGGER_PASSWORD=${WAHA_AUTHENTICATION_SWAGGER_PASSWORD}
      - WAHA_ENGINE=${WAHA_ENGINE}
      - WAHA_STORAGE_TYPE=${WAHA_STORAGE_TYPE}
      - WAHA_STORAGE_FILE_PATH=${WAHA_STORAGE_FILE_PATH}
    volumes:
      - waha_sessions:/app/sessions
    networks:
      - waha_network
volumes:
  n8n_data:
    driver: local
  waha_sessions:
    driver: local
  
networks:
  n8n-network:
    driver: bridge
  waha_network:
    driver: bridge
  